#!/usr/bin/env python3
"""Spirograph generator - create beautiful mathematical patterns.

A spirograph is a parametric curve generated by a point on the circumference
of a circle rolling inside a fixed circle. The shape depends on the ratio
of the circles' radii and the distance from the rolling circle's center.

Mathematical formula:
  x(θ) = (r1 - r2) * cos(θ) + r3 * cos(((r1 - r2) / r2) * θ)
  y(θ) = (r1 - r2) * sin(θ) - r3 * sin(((r1 - r2) / r2) * θ)

where:
  r1 = fixed circle radius
  r2 = rolling circle radius
  r3 = distance from rolling circle center to drawing point
"""

import argparse
import math
import sys
from pathlib import Path
from typing import Tuple

import svgwrite


# Named presets with characteristic parameters
PRESETS = {
    "baroque": {"r1": 250, "r2": 1, "r3": 100, "points": 250, "revolutions": 50},
    "intricate": {"r1": 300, "r2": 5, "r3": 80, "points": 400, "revolutions": 30},
    "simple": {"r1": 200, "r2": 50, "r3": 100, "points": 100, "revolutions": 10},
    "delicate": {"r1": 280, "r2": 3, "r3": 120, "points": 350, "revolutions": 40},
}


def spirograph(
    r1: float,
    r2: float,
    r3: float,
    width: int = 800,
    height: int = 800,
    points: int = 250,
    revolutions: int = 50,
    stroke_color: str = "black",
    stroke_width: float = 1.0,
) -> Tuple[int, int, list]:
    """Generate spirograph curve points.

    Args:
        r1: Radius of fixed circle
        r2: Radius of rolling circle
        r3: Distance from rolling circle center to drawing point
        width: SVG canvas width
        height: SVG canvas height
        points: Number of points to calculate
        revolutions: Number of complete revolutions
        stroke_color: Color of the drawn line
        stroke_width: Width of the line

    Returns:
        Tuple of (width, height, path_data_points)
    """
    # Calculate the angles for each point on the spirograph curve
    dtheta = revolutions * 2 * math.pi / points
    angle_list = [i * dtheta for i in range(points)]

    # Calculate the center of the image
    cx = width / 2
    cy = height / 2

    # Build path data
    path_data = []
    for i, theta in enumerate(angle_list):
        c = 1
        x = (r1 * c - r2 * c) * math.cos(theta * 2) + r3 * c * math.cos(
            ((r1 * c - r2 * c) / (r3 * c)) * theta
        )
        y = (r1 * c - r2 * c) * math.sin(theta * 2) - r3 * c * math.sin(
            ((r1 * c - r2 * c) / (r3 * c)) * theta
        )

        point = (cx + x, cy + y)
        path_data.append(point)

    return width, height, path_data


def generate_svg(
    output_path: Path,
    r1: float,
    r2: float,
    r3: float,
    width: int = 1000,
    height: int = 1000,
    points: int = 250,
    revolutions: int = 50,
    stroke_color: str = "black",
    stroke_width: float = 1.0,
) -> None:
    """Generate and save spirograph as SVG file.

    Args:
        output_path: Path to save the SVG file
        r1: Radius of fixed circle
        r2: Radius of rolling circle
        r3: Distance from rolling circle center to drawing point
        width: SVG canvas width
        height: SVG canvas height
        points: Number of points to calculate
        revolutions: Number of complete revolutions
        stroke_color: Color of the drawn line
        stroke_width: Width of the line
    """
    width_out, height_out, path_points = spirograph(
        r1, r2, r3, width, height, points, revolutions, stroke_color, stroke_width
    )

    # Create SVG drawing
    dwg = svgwrite.Drawing(str(output_path), profile="tiny")
    dwg.viewbox(0, 0, width_out, height_out)

    # Create path from points
    if path_points:
        path_data = f"M {path_points[0][0]} {path_points[0][1]}"
        for x, y in path_points[1:]:
            path_data += f" L {x} {y}"

        dwg.add(
            dwg.path(
                d=path_data,
                fill="none",
                stroke=stroke_color,
                stroke_width=stroke_width,
            )
        )

    dwg.save()
    print(f"✓ Generated: {output_path}")


def main():
    """CLI entry point for spirograph generator."""
    parser = argparse.ArgumentParser(
        prog="spirograph",
        description="Generate beautiful spirograph patterns using mathematics.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --preset baroque -o baroque.svg
  %(prog)s --r1 250 --r2 1 --r3 100 -o custom.svg
  %(prog)s --r1 300 --r2 5 --r3 80 --points 400 --revolutions 30 -o intricate.svg

Presets: """ + ", ".join(PRESETS.keys()),
    )

    parser.add_argument(
        "--preset",
        choices=list(PRESETS.keys()),
        help="Use a named preset (overrides --r1, --r2, --r3 if specified)",
    )
    parser.add_argument(
        "--r1",
        type=float,
        default=250,
        help="Radius of fixed circle (default: 250)",
    )
    parser.add_argument(
        "--r2",
        type=float,
        default=1,
        help="Radius of rolling circle (default: 1)",
    )
    parser.add_argument(
        "--r3",
        type=float,
        default=100,
        help="Distance from rolling circle center to drawing point (default: 100)",
    )
    parser.add_argument(
        "--points",
        type=int,
        default=250,
        help="Number of curve points to calculate (default: 250)",
    )
    parser.add_argument(
        "--revolutions",
        type=int,
        default=50,
        help="Number of complete revolutions (default: 50)",
    )
    parser.add_argument(
        "--width",
        type=int,
        default=1000,
        help="SVG canvas width in pixels (default: 1000)",
    )
    parser.add_argument(
        "--height",
        type=int,
        default=1000,
        help="SVG canvas height in pixels (default: 1000)",
    )
    parser.add_argument(
        "--color",
        type=str,
        default="black",
        help="Stroke color (default: black)",
    )
    parser.add_argument(
        "--stroke-width",
        type=float,
        default=1.0,
        help="Stroke width in pixels (default: 1.0)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("spirograph.svg"),
        help="Output file path (default: spirograph.svg)",
    )
    parser.add_argument(
        "-d",
        "--directory",
        type=Path,
        default=Path("./output"),
        help="Output directory (default: ./output)",
    )

    args = parser.parse_args()

    # Use preset if specified
    if args.preset:
        preset = PRESETS[args.preset]
        r1 = preset["r1"]
        r2 = preset["r2"]
        r3 = preset["r3"]
        points = preset["points"]
        revolutions = preset["revolutions"]
        preset_name = args.preset
    else:
        r1 = args.r1
        r2 = args.r2
        r3 = args.r3
        points = args.points
        revolutions = args.revolutions
        preset_name = "custom"

    # Create output directory if it doesn't exist
    output_dir = args.directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Determine output file path
    if args.output != Path("spirograph.svg"):
        output_file = args.output
    else:
        output_file = output_dir / f"spirograph_{preset_name}.svg"

    # Generate spirograph
    print(
        f"Generating spirograph: r1={r1}, r2={r2}, r3={r3}, points={points}, revolutions={revolutions}"
    )
    generate_svg(
        output_file,
        r1,
        r2,
        r3,
        args.width,
        args.height,
        points,
        revolutions,
        args.color,
        args.stroke_width,
    )
    print(f"✓ Saved to: {output_file}")


if __name__ == "__main__":
    main()
